version: '3.8' 

services:
  db:
    build: .
    container_name: mysql_Trabalho_Final_FDB
    restart: always  
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: olympic_participation
    ports:
      - "3306:3306"  
